homeYantra/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('polls.urls')), 
]

polls/urls.py
from django.conf.urls import url
from polls import views
app_name = 'polls'
urlpatterns = [
url(r'^$', views.login_page, name='login_page'),
url(r'^signup/$', views.signup, name='signup'),
url(r'^signup_fun/$', views.signup_fun, name='signup_fun'),
url(r'^check/$', views.check, name='check'), 
url(r'^moreInfo/$', views.moreInfo, name='moreInfo'), 
url(r'^moreInfoUpdate/$', views.moreInfoUpdate, name='moreInfoUpdate'), 
url(r'^database/$', views.database, name='database'), 


]

polls/models.py
from django.db import models

from django.contrib.auth.models import User


class Data(models.Model):
    pin = models.IntegerField(blank=False, null=False)
    user = models.OneToOneField(User, blank=False, null=False)
    address = models.CharField(blank=False,null=False,max_length=100)

polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate


from polls.models import  Data

def login_page(request):   
    return render(request,'polls/login_page.html',context={})
    
def check(request):
    user = authenticate(username=request.POST['email'], password=request.POST['password'])
    if user:
        if user.is_active :
            login(request, user)
            return HttpResponseRedirect(reverse('polls:moreInfo'))
        else :
            HttpResponse('you are not active !')
    return HttpResponse('incorrect username or password !' )


def moreInfo(request):
    if request.user.is_authenticated:
        return render(request, 'polls/moreInfo.html', context={})
    return HttpResponse('user is not authenticated !')
    
def moreInfoUpdate(request):
    if request.user.is_authenticated:
        if request.method == 'post':
            Data.objects.create(user = request.user, pin = request.POST['pin'], address = request.POST['address'])
            HttpResponseRedirect(reverse('polls:database'))
        else: return HttpResponseRedirect(reverse('polls:database'))
    return HttpResponseRedirect(reverse('polls:database'))

def database(request):
    return HttpResponse('page creation is in progress !')

def signup(request):
    context = {}
    return render(request, 'polls/signup.html', context)
def signup_fun(request):
    
    if request.POST['password'] != request.POST['confirm_password']:
        return HttpResponse('password does not match')
    else:
        User.objects.create_user(username=request.POST['email'], email=request.POST['email'], password=request.POST['password'])



        return HttpResponseRedirect(reverse('polls:login_page'))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load static %}

<link rel='stylesheet' type='text/css' href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
	{{question_list}}
{% endif %}

polls/templates/polls/login_page.html
<form action="{% url 'polls:check' %}" method='post'>
{% csrf_token %}
<label>username</label>  <input type='text' name='email'/> <br/>
<label>password</label>  <input type='password' name='password'/> <br/>
<input type='submit'/>
</form>



polls/templates/polls/moreInfo.html
<h1>signup information</h1>
<form action="{% url 'polls:moreInfoUpdate' %}" method='post'>
{% csrf_token %}
<label>Address:</label>  <input type='text' name='address' /> <br/>
<label>PIN Code:</label>  <input type='number' name='pin' /> <br/>
<input type='submit' value='submit' />
</form>

polls/templates/polls/question_list.html
{% if question_list %}
	<ul>
	{% for question in question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/signup.html
<h1>signup information</h1>
<form action="{% url 'polls:signup_fun' %}" method='post'>
{% csrf_token %}
<label>email address:</label>  <input type='email' name='email' /> <br/>
<label>password:</label>  <input type='password' name='password' /> <br/>
<label>confirm password:</label>  <input type='password' name='confirm_password' /> <br/>
<input type='submit' value='submit' />
</form>

polls/templates/polls/take_email.html
<h1>email confermation <h1/>
<form action="{% url 'polls:con_email' %}" method='post'>
{% csrf_token %}
<label>email</label>  <input type='text' name='email'/> <br/>
<input type='submit'/>
</form>